apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: my-api
          image: juliocesar/app:main
          imagePullPolicy: Always

          startupProbe:
            httpGet:
              path: /healthcheck
              port: 3000 # must be the port of container
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /healthcheck # should be different liveness and readiness
              port: 3000 # must be the port of container
              scheme: HTTP
            initialDelaySeconds: 10 # seconds to wait for the application to be up
            periodSeconds: 10 #
            timeoutSeconds: 2 # timeout in seconds
            failureThreshold: 2 # quantity of failures
            successThreshold: 1 # quantity of successes

          readinessProbe:
            httpGet:
              path: /healthcheck # should be different liveness and readiness
              port: 3000 # must be the port of container
              scheme: HTTP

          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DATABASE
              value: users
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
              name: http
          # - containerPort: 443
          #   name: https
