apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-app
  ports:
    - port: 80
      targetPort: 3000
      name: http
    # - port: 443
    #   targetPort: 443
    #   name: https
  type: LoadBalancer
